begin;
select plan(4);

select ok(position('where transition_key=p_transition_key' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)) < position('m26_lock_device_authority_v1(p_device_id)' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)), 'exact transition replay precedes mutable device authority locking');
select ok(position('m26_lock_device_authority_v1(p_device_id)' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)) < position('pg_advisory_xact_lock(hashtext(''m26_repository_authority''))' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)), 'commissioning mutations take device authority before repository certification authority');
select ok(position('pg_advisory_xact_lock(hashtext(''m26_repository_authority''))' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)) < position('from public.m24f_adapter_candidates where id=p_candidate_id' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)) and position('pg_advisory_xact_lock(hashtext(''m26_repository_authority''))' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)) < position('m26_current_certification_run_v1(p_candidate_id,p_manifest_id)' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)), 'repository lock precedes candidate and current certification reads');
select ok(position('m26_current_certification_run_v1(p_candidate_id,p_manifest_id)' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)) < position('where gps_device_id=p_device_id' in pg_get_functiondef('public.admin_transition_physical_pilot_commissioning_v1(uuid,uuid,uuid,bigint,uuid,text,text,text,integer)'::regprocedure)), 'certification authority is frozen before the commissioning row is locked and mutated');

select * from finish();
rollback;
